insert into BRANCH_DEPARTMENT (ID, STATUS, CREATE_LOAN_IND, BOOK_LOAN_IND, BRANCH_CODE, BRANCH_NAME, BRANCH_MANAGER, PHONE_NO, FAX_NO, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, DOC_TEXT1, DOC_TEXT2, DOC_TEXT3, DOC_TEXT4, PROVINCE, CITY, TOWN, VILLAGE, VERSION, LAST_UPDATE_USER_ID, LAST_UPDATE_DATETIME, SERIALNUMBER)
values ('1', 'A', 'N', 'N', 'HO', '浩森時貸總行', '王文波', '', '', '深圳市宝安区西乡街道宝源路财富港大厦D座4层', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0');

insert into BRANCH_DEPARTMENT (ID, STATUS, CREATE_LOAN_IND, BOOK_LOAN_IND, BRANCH_CODE, BRANCH_NAME, BRANCH_MANAGER, PHONE_NO, FAX_NO, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, DOC_TEXT1, DOC_TEXT2, DOC_TEXT3, DOC_TEXT4, PROVINCE, CITY, TOWN, VILLAGE, VERSION, LAST_UPDATE_USER_ID, LAST_UPDATE_DATETIME, SERIALNUMBER)
values ('100', 'A', 'Y', 'Y', '100', '财富港分行', '李師宏', '', '', '深圳市宝安区西乡街道宝源路财富港大厦D座4层', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0');

insert into BRANCH_DEPARTMENT (ID, STATUS, CREATE_LOAN_IND, BOOK_LOAN_IND, BRANCH_CODE, BRANCH_NAME, BRANCH_MANAGER, PHONE_NO, FAX_NO, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, DOC_TEXT1, DOC_TEXT2, DOC_TEXT3, DOC_TEXT4, PROVINCE, CITY, TOWN, VILLAGE, VERSION, LAST_UPDATE_USER_ID, LAST_UPDATE_DATETIME, SERIALNUMBER)
values ('888', 'A', 'Y', 'N', '888', '客戶服務部', '刁柳苑', '', '', '深圳市宝安区西乡街道宝源路财富港大厦D座4层', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0');

insert into BRANCH_DEPARTMENT (ID, STATUS, CREATE_LOAN_IND, BOOK_LOAN_IND, BRANCH_CODE, BRANCH_NAME, BRANCH_MANAGER, PHONE_NO, FAX_NO, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, DOC_TEXT1, DOC_TEXT2, DOC_TEXT3, DOC_TEXT4, PROVINCE, CITY, TOWN, VILLAGE, VERSION, LAST_UPDATE_USER_ID, LAST_UPDATE_DATETIME, SERIALNUMBER)
values ('2', 'A', 'N', 'N', 'COL', '账户保全部', '朱敏虹', '', '', '深圳市宝安区西乡街道宝源路财富港大厦D座4层', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0');

insert into BRANCH_DEPARTMENT (ID, STATUS, CREATE_LOAN_IND, BOOK_LOAN_IND, BRANCH_CODE, BRANCH_NAME, BRANCH_MANAGER, PHONE_NO, FAX_NO, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, DOC_TEXT1, DOC_TEXT2, DOC_TEXT3, DOC_TEXT4, PROVINCE, CITY, TOWN, VILLAGE, VERSION, LAST_UPDATE_USER_ID, LAST_UPDATE_DATETIME, SERIALNUMBER)
values ('3', 'A', 'N', 'N', 'MKT', '市场部', '阮世好', '', '', '深圳市宝安区西乡街道宝源路财富港大厦D座4层', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0');

insert into BRANCH_DEPARTMENT (ID, STATUS, CREATE_LOAN_IND, BOOK_LOAN_IND, BRANCH_CODE, BRANCH_NAME, BRANCH_MANAGER, PHONE_NO, FAX_NO, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, DOC_TEXT1, DOC_TEXT2, DOC_TEXT3, DOC_TEXT4, PROVINCE, CITY, TOWN, VILLAGE, VERSION, LAST_UPDATE_USER_ID, LAST_UPDATE_DATETIME, SERIALNUMBER)
values ('101', 'A', 'Y', 'Y', '101', '龙华分行', '肖端', '', '', '深圳市宝安区西乡街道宝源路财富港大厦D座4层', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0');

